blank_issues_enabled: false
contact_links:
  - name: ğŸ¨ Preset request 
    url: https://github.com/GradienceTeam/Community/issues/new?assignees=&labels=enhancement%2Cpreset+request&template=preset_request.yml&title=feat%3A+
  - name: ğŸ”Œ Plug-in request
    url: 
  - name: ğŸš€ GitHub Community
    url: https://github.com/orgs/GradienceTeam/discussions
    about: Please ask and answer questions here.
  - name: ğŸ“¬ Matrix
    url: https://matrix.to/#/#Gradience:matrix.org
    about: Chat on matrix.
  - name: ğŸï¸ Share your presets
    url: https://GitHub.com/Gradienceteam/Community
    about: Share your presets and see them in the explore tab
