blank_issues_enabled: false
contact_links:
  - name: GitHub Community
    url: https://github.com/orgs/AdwCustomizerTeam/discussions
    about: Please ask and answer questions here.
  - name: Matrix
    url: https://matrix.to/#/#AdwCustomizer:matrix.org
    about: Chat on matrix.
