name: Weekly Report
on:
  schedule:
    - cron: '0 6 * * 0' # At 06:00 on Sunday
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/activity-report@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
